### ISSUE TITLE
SWN Tools: Add Ship sheet button is unresponsive. 

### ISSUE THREAD

**Issue by HappySonderer** [rster2002/rster2002.github.io#194]
I actual just wanted to tell you your project is awesome. Is there a way I can show my support or help?

**Comment by rster2002** [comment]
I'm glad you like it! I'm a bit of a control freak :sweat_smile: so I'm a bit hesitant about people helping, but if you know how json works you maybe can look into companion.json (it's under /build/src/json). It contains summeries about some rules. Ships are not yet implemented. My focus now is on finishing the character sheet.

**Comment by rster2002** [comment]
Ship's are not renamed to 'groups' and are in the work.
